# This is a basic workflow to help you get started with Actions

name: R Conda

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    env:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
    defaults:
      run:
        shell: bash -l {0}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Create conda environment
        uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: recetox-aplcms-dev
          auto-update-conda: true
          environment-file: conda/environment-dev.yaml
          auto-activate-base: false
      - run: |
          conda init bash
          conda env list
          conda list
      - name: Fetch test data
        run: |
          wget -P tests/testdata/adjusted -i tests/remote-files/adjusted.txt
          wget -P tests/testdata/aligned -i tests/remote-files/aligned.txt
          wget -P tests/testdata/extracted -i tests/remote-files/extracted.txt
          wget -P tests/testdata/input -i tests/remote-files/input.txt
          wget -P tests/testdata/recovered -i tests/remote-files/recovered.txt
          wget -P tests/testdata/recovered/recovered-extracted -i tests/remote-files/recovered-extracted.txt
          wget -P tests/testdata/recovered/recovered-corrected -i tests/remote-files/recovered-corrected.txt
          wget -P tests/testdata/filtered -i tests/remote-files/filtered.txt
          wget -P tests/testdata/filtered/run_filter -i tests/remote-files/run_filter.txt
          wget -P tests/testdata/features -i tests/remote-files/features.txt
          wget -P tests/testdata/clusters -i tests/remote-files/clusters.txt
          wget -P tests/testdata/hybrid -i tests/remote-files/hybrid.txt
          wget -P tests/testdata/template -i tests/remote-files/template.txt
          wget -P tests/testdata/unsupervised -i tests/remote-files/unsupervised.txt

      - name: Test coverage
        run: |
          conda activate recetox-aplcms-dev
          Rscript -e "covr::codecov(quiet = FALSE)"
